services:
  - type: web
    name: ptt-gossiping-live # 您可以換成您自己的服務名稱
    env: docker # [FIX] 改為使用 Docker 環境，這是最穩健的作法
    plan: free
    # Docker 環境會使用 Dockerfile 來建置，不再需要 buildCommand 和 startCommand
    dockerfilePath: ./Dockerfile 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ptt-pni-database # 請換成您自己的資料庫名稱
          property: connectionString
      - key: ADMIN_SECRET_KEY
        # 為了安全，這個密碼不會跟著 GitHub 同步
        # 您需要在部署後，手動前往 Render 儀表板的 Environment 分頁設定
        sync: false 
