services:
  - type: web
    name: ptt-gossiping-live # 您可以換成您自己的服務名稱
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # [FIX] 移除 --with-deps 參數，以避免權限問題
      playwright install chromium
    startCommand: uvicorn ptt_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ptt-pni-database # 請換成您自己的資料庫名稱
          property: connectionString
      - key: ADMIN_SECRET_KEY
        sync: false # 請記得在 Render 儀表板上手動設定此密碼
      - key: PYTHON_VERSION
        value: 3.11.4
